FROM python:3.13-slim

ENV TZ="America/Santiago"

WORKDIR /code
COPY ./requirements.txt /code/requirements.txt

RUN apt-get update
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY /app /code/app

EXPOSE 8080
CMD ["fastapi", "run", "app/main.py", "--host", "0.0.0.0", "--port", "8080"]