FROM node:22-slim AS build-step
ARG ENV_BUILD=dev
WORKDIR /app
COPY . .
RUN npm install
RUN npx --no-install ng build -c $ENV_BUILD

FROM nginx:latest AS prod-step
COPY --from=build-step /app/dist/frontend/browser/ /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY default.conf /etc/nginx/conf.d/
EXPOSE 80
CMD ["nginx","-g","daemon off;"]